# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: directory.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='directory.proto',
  package='Directory',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64irectory.proto\x12\tDirectory\"\x18\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"$\n\x08\x43lientIP\x12\n\n\x02IP\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"c\n\x08\x46ileInfo\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12&\n\tclient_ip\x18\x02 \x01(\x0b\x32\x13.Directory.ClientIP\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\x12\x0e\n\x06hostID\x18\x04 \x01(\t\"\x14\n\x04\x42ool\x12\x0c\n\x04isOK\x18\x01 \x01(\x08\"5\n\x0e\x46ileSimpleInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\"L\n\x0b\x41\x64\x64\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x02\x32\x80\x03\n\tDirectory\x12:\n\x10get_file_address\x12\x0f.Directory.File\x1a\x13.Directory.FileInfo\"\x00\x12=\n\x10\x61\x64\x64_file_address\x12\x16.Directory.AddFileInfo\x1a\x0f.Directory.Bool\"\x00\x12@\n\x10\x64\x65l_file_address\x12\x19.Directory.FileSimpleInfo\x1a\x0f.Directory.Bool\"\x00\x12@\n\x14get_file_all_address\x12\x0f.Directory.File\x1a\x13.Directory.FileInfo\"\x00\x30\x01\x12\x38\n\x0cget_all_file\x12\x0f.Directory.File\x1a\x13.Directory.FileInfo\"\x00\x30\x01\x12:\n\x0eget_all_server\x12\x0f.Directory.File\x1a\x13.Directory.ClientIP\"\x00\x30\x01\x62\x06proto3')
)




_FILE = _descriptor.Descriptor(
  name='File',
  full_name='Directory.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='Directory.File.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=54,
)


_CLIENTIP = _descriptor.Descriptor(
  name='ClientIP',
  full_name='Directory.ClientIP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IP', full_name='Directory.ClientIP.IP', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Directory.ClientIP.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=92,
)


_FILEINFO = _descriptor.Descriptor(
  name='FileInfo',
  full_name='Directory.FileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='Directory.FileInfo.file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_ip', full_name='Directory.FileInfo.client_ip', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Directory.FileInfo.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostID', full_name='Directory.FileInfo.hostID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=193,
)


_BOOL = _descriptor.Descriptor(
  name='Bool',
  full_name='Directory.Bool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isOK', full_name='Directory.Bool.isOK', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=215,
)


_FILESIMPLEINFO = _descriptor.Descriptor(
  name='FileSimpleInfo',
  full_name='Directory.FileSimpleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='Directory.FileSimpleInfo.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Directory.FileSimpleInfo.timestamp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=270,
)


_ADDFILEINFO = _descriptor.Descriptor(
  name='AddFileInfo',
  full_name='Directory.AddFileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='Directory.AddFileInfo.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Directory.AddFileInfo.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Directory.AddFileInfo.port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Directory.AddFileInfo.timestamp', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=348,
)

_FILEINFO.fields_by_name['client_ip'].message_type = _CLIENTIP
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['ClientIP'] = _CLIENTIP
DESCRIPTOR.message_types_by_name['FileInfo'] = _FILEINFO
DESCRIPTOR.message_types_by_name['Bool'] = _BOOL
DESCRIPTOR.message_types_by_name['FileSimpleInfo'] = _FILESIMPLEINFO
DESCRIPTOR.message_types_by_name['AddFileInfo'] = _ADDFILEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'directory_pb2'
  # @@protoc_insertion_point(class_scope:Directory.File)
  })
_sym_db.RegisterMessage(File)

ClientIP = _reflection.GeneratedProtocolMessageType('ClientIP', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTIP,
  '__module__' : 'directory_pb2'
  # @@protoc_insertion_point(class_scope:Directory.ClientIP)
  })
_sym_db.RegisterMessage(ClientIP)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFO,
  '__module__' : 'directory_pb2'
  # @@protoc_insertion_point(class_scope:Directory.FileInfo)
  })
_sym_db.RegisterMessage(FileInfo)

Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), {
  'DESCRIPTOR' : _BOOL,
  '__module__' : 'directory_pb2'
  # @@protoc_insertion_point(class_scope:Directory.Bool)
  })
_sym_db.RegisterMessage(Bool)

FileSimpleInfo = _reflection.GeneratedProtocolMessageType('FileSimpleInfo', (_message.Message,), {
  'DESCRIPTOR' : _FILESIMPLEINFO,
  '__module__' : 'directory_pb2'
  # @@protoc_insertion_point(class_scope:Directory.FileSimpleInfo)
  })
_sym_db.RegisterMessage(FileSimpleInfo)

AddFileInfo = _reflection.GeneratedProtocolMessageType('AddFileInfo', (_message.Message,), {
  'DESCRIPTOR' : _ADDFILEINFO,
  '__module__' : 'directory_pb2'
  # @@protoc_insertion_point(class_scope:Directory.AddFileInfo)
  })
_sym_db.RegisterMessage(AddFileInfo)



_DIRECTORY = _descriptor.ServiceDescriptor(
  name='Directory',
  full_name='Directory.Directory',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=351,
  serialized_end=735,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_file_address',
    full_name='Directory.Directory.get_file_address',
    index=0,
    containing_service=None,
    input_type=_FILE,
    output_type=_FILEINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='add_file_address',
    full_name='Directory.Directory.add_file_address',
    index=1,
    containing_service=None,
    input_type=_ADDFILEINFO,
    output_type=_BOOL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='del_file_address',
    full_name='Directory.Directory.del_file_address',
    index=2,
    containing_service=None,
    input_type=_FILESIMPLEINFO,
    output_type=_BOOL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_file_all_address',
    full_name='Directory.Directory.get_file_all_address',
    index=3,
    containing_service=None,
    input_type=_FILE,
    output_type=_FILEINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_all_file',
    full_name='Directory.Directory.get_all_file',
    index=4,
    containing_service=None,
    input_type=_FILE,
    output_type=_FILEINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_all_server',
    full_name='Directory.Directory.get_all_server',
    index=5,
    containing_service=None,
    input_type=_FILE,
    output_type=_CLIENTIP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIRECTORY)

DESCRIPTOR.services_by_name['Directory'] = _DIRECTORY

# @@protoc_insertion_point(module_scope)
