# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file.proto',
  package='File',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nfile.proto\x12\x04\x46ile\"\x18\n\x04\x66ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x14\n\x04\x42ool\x12\x0c\n\x04isOK\x18\x01 \x01(\x08\"-\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t2\xa0\x01\n\x04\x46ile\x12\"\n\x06\x63reate\x12\n.File.file\x1a\n.File.Bool\"\x00\x12\"\n\x06\x64\x65lete\x12\n.File.file\x1a\n.File.Bool\"\x00\x12&\n\x06upload\x12\x0e.File.FileInfo\x1a\n.File.Bool\"\x00\x12(\n\x08\x64ownload\x12\n.File.file\x1a\x0e.File.FileInfo\"\x00\x62\x06proto3')
)




_FILE = _descriptor.Descriptor(
  name='file',
  full_name='File.file',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='File.file.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=44,
)


_BOOL = _descriptor.Descriptor(
  name='Bool',
  full_name='File.Bool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isOK', full_name='File.Bool.isOK', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=66,
)


_FILEINFO = _descriptor.Descriptor(
  name='FileInfo',
  full_name='File.FileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='File.FileInfo.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context', full_name='File.FileInfo.context', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['file'] = _FILE
DESCRIPTOR.message_types_by_name['Bool'] = _BOOL
DESCRIPTOR.message_types_by_name['FileInfo'] = _FILEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

file = _reflection.GeneratedProtocolMessageType('file', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:File.file)
  })
_sym_db.RegisterMessage(file)

Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), {
  'DESCRIPTOR' : _BOOL,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:File.Bool)
  })
_sym_db.RegisterMessage(Bool)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFO,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:File.FileInfo)
  })
_sym_db.RegisterMessage(FileInfo)



_FILE = _descriptor.ServiceDescriptor(
  name='File',
  full_name='File.File',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=116,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='File.File.create',
    index=0,
    containing_service=None,
    input_type=_FILE,
    output_type=_BOOL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='File.File.delete',
    index=1,
    containing_service=None,
    input_type=_FILE,
    output_type=_BOOL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='upload',
    full_name='File.File.upload',
    index=2,
    containing_service=None,
    input_type=_FILEINFO,
    output_type=_BOOL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='download',
    full_name='File.File.download',
    index=3,
    containing_service=None,
    input_type=_FILE,
    output_type=_FILEINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILE)

DESCRIPTOR.services_by_name['File'] = _FILE

# @@protoc_insertion_point(module_scope)
