# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lock.proto',
  package='Lock',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nlock.proto\x12\x04Lock\"\x17\n\x03Str\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1c\n\x08TypeLock\x12\x10\n\x08typelock\x18\x01 \x01(\x05\"$\n\x08\x43lientIP\x12\n\n\x02IP\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"0\n\nClientInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08typelock\x18\x02 \x01(\x05\"M\n\rClientAllInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\n\n\x02IP\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\x10\n\x08typelock\x18\x04 \x01(\x05\x32\xd1\x01\n\x04Lock\x12.\n\x0flock_exist_test\x12\t.Lock.Str\x1a\x0e.Lock.TypeLock\"\x00\x12\x35\n\x0fget_lock_client\x12\t.Lock.Str\x1a\x13.Lock.ClientAllInfo\"\x00\x30\x01\x12/\n\tlock_file\x12\x10.Lock.ClientInfo\x1a\x0e.Lock.TypeLock\"\x00\x12\x31\n\x0bunlock_file\x12\x10.Lock.ClientInfo\x1a\x0e.Lock.TypeLock\"\x00\x62\x06proto3')
)




_STR = _descriptor.Descriptor(
  name='Str',
  full_name='Lock.Str',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='Lock.Str.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=43,
)


_TYPELOCK = _descriptor.Descriptor(
  name='TypeLock',
  full_name='Lock.TypeLock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='typelock', full_name='Lock.TypeLock.typelock', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=73,
)


_CLIENTIP = _descriptor.Descriptor(
  name='ClientIP',
  full_name='Lock.ClientIP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IP', full_name='Lock.ClientIP.IP', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Lock.ClientIP.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=111,
)


_CLIENTINFO = _descriptor.Descriptor(
  name='ClientInfo',
  full_name='Lock.ClientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='Lock.ClientInfo.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typelock', full_name='Lock.ClientInfo.typelock', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=161,
)


_CLIENTALLINFO = _descriptor.Descriptor(
  name='ClientAllInfo',
  full_name='Lock.ClientAllInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='Lock.ClientAllInfo.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IP', full_name='Lock.ClientAllInfo.IP', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Lock.ClientAllInfo.port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typelock', full_name='Lock.ClientAllInfo.typelock', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=240,
)

DESCRIPTOR.message_types_by_name['Str'] = _STR
DESCRIPTOR.message_types_by_name['TypeLock'] = _TYPELOCK
DESCRIPTOR.message_types_by_name['ClientIP'] = _CLIENTIP
DESCRIPTOR.message_types_by_name['ClientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['ClientAllInfo'] = _CLIENTALLINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Str = _reflection.GeneratedProtocolMessageType('Str', (_message.Message,), {
  'DESCRIPTOR' : _STR,
  '__module__' : 'lock_pb2'
  # @@protoc_insertion_point(class_scope:Lock.Str)
  })
_sym_db.RegisterMessage(Str)

TypeLock = _reflection.GeneratedProtocolMessageType('TypeLock', (_message.Message,), {
  'DESCRIPTOR' : _TYPELOCK,
  '__module__' : 'lock_pb2'
  # @@protoc_insertion_point(class_scope:Lock.TypeLock)
  })
_sym_db.RegisterMessage(TypeLock)

ClientIP = _reflection.GeneratedProtocolMessageType('ClientIP', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTIP,
  '__module__' : 'lock_pb2'
  # @@protoc_insertion_point(class_scope:Lock.ClientIP)
  })
_sym_db.RegisterMessage(ClientIP)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'lock_pb2'
  # @@protoc_insertion_point(class_scope:Lock.ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

ClientAllInfo = _reflection.GeneratedProtocolMessageType('ClientAllInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTALLINFO,
  '__module__' : 'lock_pb2'
  # @@protoc_insertion_point(class_scope:Lock.ClientAllInfo)
  })
_sym_db.RegisterMessage(ClientAllInfo)



_LOCK = _descriptor.ServiceDescriptor(
  name='Lock',
  full_name='Lock.Lock',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=243,
  serialized_end=452,
  methods=[
  _descriptor.MethodDescriptor(
    name='lock_exist_test',
    full_name='Lock.Lock.lock_exist_test',
    index=0,
    containing_service=None,
    input_type=_STR,
    output_type=_TYPELOCK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_lock_client',
    full_name='Lock.Lock.get_lock_client',
    index=1,
    containing_service=None,
    input_type=_STR,
    output_type=_CLIENTALLINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='lock_file',
    full_name='Lock.Lock.lock_file',
    index=2,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_TYPELOCK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='unlock_file',
    full_name='Lock.Lock.unlock_file',
    index=3,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_TYPELOCK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCK)

DESCRIPTOR.services_by_name['Lock'] = _LOCK

# @@protoc_insertion_point(module_scope)
