# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import file_pb2 as file__pb2


class FileStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create = channel.unary_unary(
        '/File.File/create',
        request_serializer=file__pb2.file.SerializeToString,
        response_deserializer=file__pb2.Bool.FromString,
        )
    self.delete = channel.unary_unary(
        '/File.File/delete',
        request_serializer=file__pb2.file.SerializeToString,
        response_deserializer=file__pb2.Bool.FromString,
        )
    self.upload = channel.unary_unary(
        '/File.File/upload',
        request_serializer=file__pb2.FileInfo.SerializeToString,
        response_deserializer=file__pb2.Bool.FromString,
        )
    self.download = channel.unary_unary(
        '/File.File/download',
        request_serializer=file__pb2.file.SerializeToString,
        response_deserializer=file__pb2.FileInfo.FromString,
        )


class FileServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create(self, request, context):
    """创建一个文件
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    """删除一个文件 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def upload(self, request, context):
    """上传一个文件,判断是否OK
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def download(self, request, context):
    """读或下载一个文件,判断是否能读
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=file__pb2.file.FromString,
          response_serializer=file__pb2.Bool.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=file__pb2.file.FromString,
          response_serializer=file__pb2.Bool.SerializeToString,
      ),
      'upload': grpc.unary_unary_rpc_method_handler(
          servicer.upload,
          request_deserializer=file__pb2.FileInfo.FromString,
          response_serializer=file__pb2.Bool.SerializeToString,
      ),
      'download': grpc.unary_unary_rpc_method_handler(
          servicer.download,
          request_deserializer=file__pb2.file.FromString,
          response_serializer=file__pb2.FileInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'File.File', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
